### ISSUE TITLE
nse_stock_quote() Not works 

### ISSUE THREAD

**Issue by gpandi007** [rsquaredacademy/nse2r#52] opened 2021-01-18 08:44 UTC
nse_stock_quote(stock_code = 'SUNTV')

loading long time and not giving outcome 

this is applicable for all stock code not only 'SUNTV'

please check it and let me know ASP

**Comment by aravindhebbali** [comment] 2021-01-18 15:30
We are looking into this. Will update soon.

**Comment by gpandi007** [comment] 2021-01-19 07:31
> We are looking into this. Will update soon.

thanks for your reply 
please update here once done 

nse2r Package is much help full for me !!

**Comment by aravindhebbali** [comment] 2021-01-19 17:04
Hi @gpandi007,

We have zeroed in on the issue. The stock quote is scraped from the NSE website but it looks like NSE has blocked its html files from being read or downloaded. We will update once we figure a way around this.

**Comment by gpandi007** [comment] 2021-01-20 04:09
> Hi @gpandi007,
> 
> We have zeroed in on the issue. The stock quote is scraped from the NSE website but it looks like NSE has blocked its html files from being read or downloaded. We will update once we figure a way around this.

Hi Aravindhebbali,
I would suggest that stock quote can be pulled from other websites e.g: yahoofinace, Money control ect
you can modify your HTML template accordingly 

or  

you can update NSE2R package which can give preopen price for all the NSE stocks (FX stocks, all stocks)
but  now NSE2R package has limitation to get preopen price for NIFTY50 AND BANK NIXRY

NOTE:
my ML model based out of NSE2R package, if  stock quote does not works then complete Model will be fail. 

@ASAP

**Comment by aravindhebbali** [comment] 2021-01-20 04:46
Hi @gpandi007,

We will scrape from either of the above sources mentioned and ensure this works by end of day.

**Comment by gpandi007** [comment] 2021-01-21 08:38
> Hi @gpandi007,
> 
> We will scrape from either of the above sources mentioned and ensure this works by end of day.


@aravindhebbali 
hint for you Refer below link: 

https://cran.r-project.org/web/packages/quantmod/quantmod.pdf
page number 47 code getQuote()

**Comment by Ramprasad76** [comment] 2021-01-29 15:50
Hi Aravind,

Kindly look into the issue. It help greatly to build further modelling...

**Comment by aravindhebbali** [comment] 2021-01-30 05:51
Hi @Ramprasad76,

We are scraping the data from rediff. Will update once we finish testing.

**Comment by aravindhebbali** [comment] 2021-01-30 07:57
Hi @gpandi007 & @Ramprasad76,

We have used the Yahoo Finance API to get the data using the following URLs

- https://query1.finance.yahoo.com/v8/finance/chart/SUNTV.NS
- https://query2.finance.yahoo.com/v8/finance/chart/SUNTV.NS

But I am not sure if the regular market price is the real time price or the closing price. Will be able to check this on Monday and update again. Let me know if this helps and sorry for the delay in responding.

``` r
## load package
library(nse2r)

## stock quote
nse_stock_quote('SUNTV')
#> [1] 477.75
```

<sup>Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

 In rediff, constructing the URLs looks slightly complex but we hope to use it as a back up.

**Comment by aravindhebbali** [comment] 2021-01-30 11:15
Have added [Rediff Money](https://money.rediff.com/index.html) as a back up source in case the Yahoo Finance API fails. 

``` r
## load package
library(nse2r)

## stock quote from yahoo finance api
nse_stock_quote(stock_code = "infy")
#> [1] 1239.05

## stock quote from rediff money
nse_stock_quote(stock_code = "infy", source = "rediff")
#> [1] 1239.05
```

<sup>Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gpandi007** [comment] 2021-01-31 08:46
Let me check and back to you 😊

**Comment by gpandi007** [comment] 2021-02-01 10:31
> Have added [Rediff Money](https://money.rediff.com/index.html) as a back up source in case the Yahoo Finance API fails.
> 
> ```r
> ## load package
> library(nse2r)
> 
> ## stock quote from yahoo finance api
> nse_stock_quote(stock_code = "infy")
> #> [1] 1239.05
> 
> ## stock quote from rediff money
> nse_stock_quote(stock_code = "infy", source = "rediff")
> #> [1] 1239.05
> ```
> 
> Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)

issue is not solved still loading longer time and not getting output !!!

**Comment by aravindhebbali** [comment] 2021-02-01 11:02
I just tried again and got this result. 

``` r
## load package
library(nse2r)

## stock quote from yahoo finance api
nse_stock_quote(stock_code = "infy")
#> [1] 1260.9

## stock quote from rediff money
nse_stock_quote(stock_code = "infy", source = "rediff")
#> [1] 1260.9
```

<sup>Created on 2021-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aravindhebbali** [comment] 2021-02-05 05:48
Hi @gpandi007 & @Ramprasad76,

Does the issue still persist? If yes, is it possible to share any other info that might help us debug this further?

**Comment by gpandi007** [comment] 2021-02-05 06:10
> Hi @gpandi007 & @Ramprasad76,
> 
> Does the issue still persist? If yes, is it possible to share any other info that might help us debug this further?

YES this issue is not solved yet, still loading longer time not getting result 
i checked  with other PC also

**Comment by aravindhebbali** [comment] 2021-02-05 06:50
Okay.. Thanks for responding. We will look into it.

**Comment by gpandi007** [comment] 2021-02-25 08:09
Are you working on this or you issue closed !!!

**Comment by aravindhebbali** [comment] 2021-02-26 05:27
> 
> 
> Are you working on this or you issue closed !!!

Hi @gpandi007,

We tested it on Windows and on Linux (using RStudio Cloud). It worked in both the cases. We have asked a few others to test as well to see if we can get any info to debug. Is it possible for you to try again and let us know if you get any error messages? Also, can you share the output from `Sys.info()`?

**Comment by aravindhebbali** [comment] 2021-03-03 07:02
Hi @gpandi007,

We got several others to test and it works fine in all the cases. Can you install the development version of the package from GitHub and try again? Also, share the output from `Sys.info()` so that we can determine if the issue is local to any particular system.

**Closed** 2021-03-03 12:27 UTC
Labels: bug

**Comment by gpandi007** [comment] 2021-03-04 06:55
![image](https://user-images.githubusercontent.com/48507358/109923139-59729000-7ce4-11eb-906c-ee640be5eef1.png)
![image](https://user-images.githubusercontent.com/48507358/109923261-832bb700-7ce4-11eb-899d-ae96c3e75ad5.png)
![image](https://user-images.githubusercontent.com/48507358/109923315-9c346800-7ce4-11eb-877c-d1fbc000e17e.png)
please have look in to attached excel 

sorry for the delay in reply

**Comment by aravindhebbali** [comment] 2021-03-04 07:29
> 
> 
> ![image](https://user-images.githubusercontent.com/48507358/109923139-59729000-7ce4-11eb-906c-ee640be5eef1.png)
> ![image](https://user-images.githubusercontent.com/48507358/109923261-832bb700-7ce4-11eb-899d-ae96c3e75ad5.png)
> ![image](https://user-images.githubusercontent.com/48507358/109923315-9c346800-7ce4-11eb-877c-d1fbc000e17e.png)
> please have look in to attached excel
> 
> sorry for the delay in reply , you can see the result is loading longer time and not getting output

Hi @gpandi007 ,

The output from Rediff Money does take time but Yahoo Finance API has low response time. We are not sure why there is a delay.
